# Configuration for the Automated Newspaper Downloader & Emailer (Simplified)

# --- Newspaper Configuration ---
newspaper:
  # Base URL for constructing the download link
  url: "https://example.com"
  # Path pattern appended to the base URL for downloading the newspaper.
  # The {date} placeholder will be replaced with the date of the newspaper to download.
  # The format of {date} is controlled by the 'date_format' setting under 'general' (default: "%Y-%m-%d").
  # For example, if date_format is "%Y-%m-%d" and the date is 2024-06-01, the path will be "newspaper/download/2024-06-01".
  download_path_pattern: "newspaper/download/{date}"

# --- Storage Configuration ---
storage:
  endpoint_url: "https://<ACCOUNT_ID>.r2.cloudflarestorage.com"
  access_key_id: "your-access-key-id"
  secret_access_key: "your-secret-access-key"
  region: "auto"
  bucket: "newspaper-storage"

# --- General Settings ---
general:
  retention_days: 7
  date_format: "%Y-%m-%d"
  filename_template: "{date}_newspaper.{format}"
  thumbnail_filename_template: "{date}_thumbnail.{format}"

# --- Email Settings ---
email:
  sender: "sender@example.com"
  recipients:
    - "recipient1@example.com"
  subject_template: "Your Daily Newspaper - {{ date }}"
  template: "email_template.html"
  smtp_host: "smtp.example.com"
  smtp_port: 587
  smtp_user: "smtp_user@example.com"
  smtp_pass: "your-smtp-password"
  smtp_tls: 1
  alert_recipient: "admin@example.com"

# --- Paths ---
paths:
  download_dir: "downloads"
  template_dir: "templates"
  log_file: "newspaper_emailer.log"
  status_file: "pipeline_status.json"
